import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';
import { BorderRadius, Layout, Shadows, Spacing } from '../../design-system/tokens/spacing';
import { TextStyles } from '../../design-system/tokens/typography';

export const chatRoomStyles = StyleSheet.create({
  container: {
    backgroundColor: colors.background,
    flex: 1,
  },
  background: {
    bottom: 0,
    flex: 1,
    height: '100%',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  header: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: 4,
    flexDirection: 'row',
    gap: Spacing.sm,
    minHeight: Layout.headerHeight + 34,
    paddingBottom: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.xl,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  headerButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.border,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 3,
    justifyContent: 'center',
    minHeight: 42,
    minWidth: 74,
    paddingHorizontal: Spacing.md,
  },
  headerButtonText: {
    ...TextStyles.caption,
    color: colors.secondary,
    fontFamily: 'TitanOne_400Regular',
    textAlign: 'center',
  },
  headerCenter: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  headerImage: {
    height: 54,
    marginRight: Spacing.sm,
    width: 54,
  },
  headerText: {
    flexShrink: 1,
  },
  headerTitle: {
    ...TextStyles.title,
    color: colors.surfaceElevated,
    fontFamily: 'LuckiestGuy_400Regular',
    fontSize: 24,
    lineHeight: 28,
    textAlign: 'left',
  },
  statusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.xs,
  },
  statusDot: {
    borderColor: colors.border,
    borderRadius: BorderRadius.full,
    borderWidth: 2,
    height: 12,
    width: 12,
  },
  connectedDot: {
    backgroundColor: colors.success,
  },
  matchingDot: {
    backgroundColor: colors.warning,
  },
  connectionStatus: {
    ...TextStyles.small,
    color: colors.text,
    fontWeight: '700',
  },
  messagesList: {
    flex: 1,
  },
  messagesContent: {
    gap: Spacing.sm,
    paddingBottom: Spacing.xl,
    paddingHorizontal: Spacing.sm,
    paddingTop: Spacing.lg,
  },
  inputContainer: {
    alignItems: 'flex-end',
    backgroundColor: 'rgba(30, 9, 110, 0.92)',
    borderTopColor: colors.border,
    borderTopWidth: 4,
    flexDirection: 'row',
    gap: Spacing.sm,
    padding: Spacing.lg,
  },
  textInput: {
    ...TextStyles.body,
    backgroundColor: '#ffffff',
    borderColor: colors.border,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 3,
    color: colors.secondary,
    flex: 1,
    maxHeight: 120,
    minHeight: Layout.inputHeight,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    textAlignVertical: 'top',
    ...Shadows.md,
  },
  sendButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.border,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 3,
    height: Layout.minTouchTarget + 6,
    justifyContent: 'center',
    minWidth: 82,
    paddingHorizontal: Spacing.md,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
  },
  sendButtonDisabled: {
    opacity: 0.55,
  },
  sendButtonText: {
    color: colors.secondary,
    fontFamily: 'TitanOne_400Regular',
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
  },
});
